prometheusOperator:
  # 此处省略其他配置项
  prometheusSpec:
    # 此处省略其他配置项
    additionalScrapeConfigs:
      - job_name: scrapycompositedemo
        static_configs:
          - labels:
              app: scrapycompositedemo
            targets:
              - scrapycompositedemo.crawler.svc.cluster.local:9410