apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgresql
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - image: postgres:9.4
          name: postgresql
          resources:
            requests:
              memory: 1Gi
              cpu: 400m
            limits:
              memory: 1Gi
              cpu: 400m
          env:
            - name: PGDATA
              value: /data
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql
                  key: PGSQL_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql
                  key: PGSQL_USER
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /data
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |
              mkdir -p /data
              chmod -R 777 /data
          image: docker.io/bitnami/minideb:stretch
          imagePullPolicy: Always
          name: init-chmod-data
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsUser: 0
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgresql
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql