apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jmeter
  name: jmeter-cuiqingcai-com
  namespace: jmeter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: jmeter
    spec:
      containers:
        - args:
            - cuiqingcai.com.jmx
          image: germey/jmeter
          name: jmeter-cuiqingcai-com
          volumeMounts:
            - mountPath: /app
              name: jmeter-storage
      restartPolicy: Always
      volumes:
        - name: jmeter-storage
          persistentVolumeClaim:
            claimName: pvc-jmeter
