apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scrapyd
  namespace: scrapyd
spec:
  storageClassName: azure-file
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi