apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
#  storageAccount: ff4521f7d94024bc0a41772
allowVolumeExpansion: true
volumeBindingMode: Immediate