apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-proxypool
  namespace: proxypool
spec:
  storageClassName: azure-file
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi